jobs:
- job: Build
  strategy:
    matrix:
      darwin_amd64:
        name: "darwin_amd64"
        suffix: ""
        GOOS: "darwin"
        GOARCH: "amd64"
      darwin_arm64:
        name: "darwin_arm64"
        suffix: ""
        GOOS: "darwin"
        GOARCH: "arm64"
      linux_amd64:
        name: "linux_amd64"
        suffix: ""
        GOOS: "linux"
        GOARCH: "amd64"
      linux_arm:
        name: "linux_arm"
        suffix: ""
        GOOS: "linux"
        GOARCH: "arm"
      linux_arm64:
        name: "linux_arm64"
        suffix: ""
        GOOS: "linux"
        GOARCH: "arm64"
      raspberrypi_arm:
        name: "raspberrypi_arm"
        suffix: ""
        GOOS: "linux"
        GOARCH: "arm"
        GOARM: "5"
      windows_amd64:
        name: "windows_amd64"
        suffix: ".exe"
        GOOS: "windows"
        GOARCH: "amd64"
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 30
  steps:
  - task: GoTool@0
    inputs:
      version: '1.21.7'
  - task: Go@0
    inputs:
      command: 'build'
      arguments: '-a -tags netgo -ldflags "-w -extldflags "-static"" -o noxon-server_$(name)$(suffix) cmd/main.go'
  - task: CopyFiles@2
    inputs:
      Contents: 'noxon-server*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: noxon-server
